const ITEM_TYPE = {
  SERVICE: 'SERVICE',
  REQUEST: 'REQUEST',
};

const OFFER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
};

export { ITEM_TYPE, OFFER_STATUS };
